### ISSUE TITLE
Cannot update a goal anymore when viewing manage goals twice

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#19067]
This is with Matomo 4.8 on PHP8

I'm trying to edit a goal like this:
<img width="252" alt="image" src="https://user-images.githubusercontent.com/273120/162359862-ac261a9f-04ef-4c83-9f30-2add68b13684.png">

but no funnels configuration shows up and no update button.

seeing in console this error:
<img width="693" alt="image" src="https://user-images.githubusercontent.com/273120/162359845-db0bf2f8-f8fa-4456-b671-fc3e8750498b.png">

call stack: 
<img width="336" alt="image" src="https://user-images.githubusercontent.com/273120/162360018-53a1bff2-9a70-46cd-ab71-ec503d57541a.png">
<img width="357" alt="image" src="https://user-images.githubusercontent.com/273120/162360098-38523604-c372-4284-a4ba-b8281dd752f1.png">
<img width="1308" alt="image" src="https://user-images.githubusercontent.com/273120/162360130-ea8c90c5-856d-407c-ad17-35176a1d167e.png">

This is happening in our own Matomo.

To reproduce I followed these steps

*  opened "Manage Goals" `/index.php?module=CoreHome&action=index&idSite=12&period=week&date=today#?idSite=12&period=day&date=2022-04-08&category=Goals_Goals&subcategory=Goals_ManageGoals`
* Then clicked on "Manage Goals"  again

Then the JS error happens and you can't edit anything anymore.
This must be a regression.

**Comment by sgiehl** [comment]
Seems this was already fixed. I'm able to reproduce that locally with `4.8.0`, but with `4.9.0-rc1` this doesn't happen anymore.

**Comment by tsteur** [comment]
👍  feel free to close in that case

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/plugin-goals-error-after-update-4-9-0/45519/3

**Comment by niklasternstedt** [comment]
It is still a problem if a want to add a new goal when I don't have any goals. Then I get this error message:
`Oops… there was a problem during the request. Maybe the server had a temporary issue, or maybe you requested a report with too much data. Please try again. If this error occurs repeatedly please contact your Matomo administrator for assistance. [See the steps to resolve this issue in the FAQ.](https://matomo.org/faq/troubleshooting/faq_19489/)`

**Comment by koljam** [comment]
> It is still a problem if a want to add a new goal when I don't have any goals. Then I get this error message: `Oops… there was a problem during the request. Maybe the server had a temporary issue, or maybe you requested a report with too much data. Please try again. If this error occurs repeatedly please contact your Matomo administrator for assistance. [See the steps to resolve this issue in the FAQ.](https://matomo.org/faq/troubleshooting/faq_19489/)`

There seems to be a workaround until there is a new release: https://github.com/matomo-org/matomo/issues/19124#issuecomment-1104636551

**Comment by sgiehl** [comment]
@koljam a first release candidate for Matomo 4.10.0 will be released next week. That one should fix this issue.
