### ISSUE TITLE
Visitor log: Title and urls are cut too early

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#5229]
In Visitor Log there is lots of unused whitespace, because title and urls in the right column are cut very early. 

See #5220 and http://issues.piwik.org/attachments/5220/2014-05-23_17h11_39.png

**Comment by tsteur** [comment]
The unused white space on the left was already fixed in an earlier version. Still labels are truncated too early.

**Comment by tsteur** [comment]
I tried to work on it but I think the whole CSS and HTML structure needs to be changed there.

**Comment by ThaDafinser** [comment]
With FF35 and Piwik 2.10 i dont see this issue.

But a similar issue (and still valid) is this one: https://github.com/piwik/piwik/issues/5915

**Comment by mattab** [comment]
can still reproduce it at: http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=32&period=day&date=yesterday#/module=Live&action=indexVisitorLog&idSite=32&period=day&date=yesterday

**Comment by tsteur** [comment]
See comment above. I did write to fix it properly we need to change the whole HTML structure of the VisitorLog (and therefore also parts of VisitorProfile etc)

**Comment by mattab** [comment]
Ok, then removing Easy pick and decreasing priority

**Comment by tsteur** [comment]
It might be still easy as it's mainly html/css etc. Just a lot of work. 

I added the Design/UI label so if someone wants to look for html/css stuff one can rather find it. Not sure if it is actually Usability.

**Comment by sogen** [comment]
Can this be closed? 
The new version has a completely different Design/UI

**Comment by sgiehl** [comment]
Guess so. There is much more space used now if available.
