### ISSUE TITLE
Call to undefined method Piwik\Updater::addComponentToCheck()

### ISSUE THREAD

**Issue by yjajkiew** [piwik/piwik#7753]
Hello ! 

I'm creating this issue because after an automatic update from 2.10.0 to 2.12 I am now having the following error : 

    Fatal error: Call to undefined method Piwik\Updater::addComponentToCheck() in /homepages/16/d410276458/htdocs/piwik/plugins/CoreUpdater/CoreUpdater.php on line 131

    Fatal error: Uncaught exception 'Zend_Session_Exception' with message 'Session must be started before any output has been sent to the browser; output started in /homepages/16/d410276458/htdocs/piwik/plugins/CoreUpdater/CoreUpdater.php/131' in /homepages/16/d410276458/htdocs/piwik/libs/Zend/Session.php:443 Stack trace: #0 /homepages/16/d410276458/htdocs/piwik/libs/Zend/Session/Namespace.php(143): Zend_Session::start(true) #1 /homepages/16/d410276458/htdocs/piwik/core/Session/SessionNamespace.php(34): Zend_Session_Namespace->__construct('CorePluginsAdmi...', false) #2 /homepages/16/d410276458/htdocs/piwik/core/Nonce.php(39): Piwik\Session\SessionNamespace->__construct('CorePluginsAdmi...') #3 /homepages/16/d410276458/htdocs/piwik/plugins/CorePluginsAdmin/Controller.php(364): Piwik\Nonce::getNonce('CorePluginsAdmi...') #4 [internal function]: Piwik\Plugins\CorePluginsAdmin\Controller->safemode(Array) #5 /homepages/16/d410276458/htdocs/piwik/core/FrontController.php(530): call_user_func_array(Array, Array) #6 /homepages/16/d4 in /homepages/16/d410276458/htdocs/piwik/libs/Zend/Session.php on line 443

I have found these 2 similar errors : 
- http://forum.piwik.org/read.php?2,125451
- http://forum.piwik.org/read.php?2,125592

In those posts the solution is to manually update Piwik, so obviously that's what I did via SSH commands : 
$ wget http://builds.piwik.org/piwik.zip # download latest version
$ unzip -o piwik.zip # extract it to "piwik/" directory
$ rm piwik.zip # delete the archive and read below the next step

But it doesn't work at all and the same error message appears :/ 
I also tried to put back the 2.10.0 piwik files in my folder and the problem still is the same. 
In my database the piwik version is 2.10.0 

I created a post in the support section of the piwik forum available here : http://forum.piwik.org/read.php?2,126138

We tried to add chmod 777 permissions to the tmp folder, and I also tried to upload the last release 2.13.0 release candidate.

As suggested by Matt it might be bug.

**Comment by mnapoli** [comment]
Hi, for the first error I have to insist that the Piwik files are not correct, maybe they were not overwritten correctly when you unzipped? I'm saying that because the error happens at line 131 of [plugins/CoreUpdater/CoreUpdater.php](https://github.com/piwik/piwik/blob/master/plugins/CoreUpdater/CoreUpdater.php) but this file only has 80 lines in the latest release.

Could you check the content of this file, and reupload the latest version again and check it matches the version I linked to (by the way we just released 2.13.0.

The second error is probably because of the first one.

**Comment by mattab** [comment]
Also restart your webserver, you may have some caching going on? maybe upgrade to 2.13.0 released today in case we're lucky and this may fix it?

**Comment by yjajkiew** [comment]
Hi,

I used SSH again to get the last piwik version and unzip it in my piwik folder and the error still appeared. So I checked the number of lines of the CoreUpdater.php file and there was a delta between my file and the original file downloaded... Apparently the unzip command via SSH, even with -o parameter, doesn't overwrite very well the files.

I uploaded the latest piwik version manually using FTP and now it works !

Problem solved, thank you !

**Comment by mnapoli** [comment]
Glad to know thanks.
