### ISSUE TITLE
UI tests might take a screenshot of a different test / test suite if there's a JS error or so

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#8033]
It is hard to explain but I'll do my best. In this PR I added a test to `ActionsDataTable`: https://github.com/piwik/piwik/pull/8018/files#diff-be9457c4f00490761508a5b7d36a8140R95

There under circumstances it was possible that a JS error happens which causes the test to "pause/wait" for like 2 minutes or so. Not quite sure. Meanwhile the next suits `BarGraph` started which caused for my tests in `ActionsDataTable` to be taken a screenshot of BarGraph see http://builds-artifacts.piwik.org/ui-tests.master/13001.7/processed-ui-screenshots/ActionsDataTable_auto_expand.png . It took me a long time to figure out what is going on since it worked for me locally and there's not really a way that it could show a bar graph for the PageURLs report etc. 

If there's a JS error or so can we maybe report this error immediately and not wait? But maybe take a screenshot immediately though to better be able to analyze it?

**Comment by diosmosis** [comment]
The new test suite (ie, BarGraph) should do a page load, so it shouldn't be affected by the previous suite. This might be a random phantomjs issue. Sometimes, it takes a screenshot of the last page loaded, instead of the current one. I'm not sure why it happens, and I thought I fixed it by recreating the webpage on each load, instead of reusing them.

**Comment by mattab** [comment]
> If there's a JS error or so can we maybe report this error immediately and not wait? 

@tsteur you maybe implemented this feature, since creating this issue?

**Comment by tsteur** [comment]
Not really, it can still occur. Can close it though until we see it again somewhere. Reckon will be very hard to fix anyway
