### ISSUE TITLE
Goal Tracking Broken Since 2.15.0-b1 update

### ISSUE THREAD

**Issue by ericimprint** [piwik/piwik#8622]
I have a basic regex goal of `thanks4quote|/confirm/quote`. Since upgrading to 2.15.0-b1 it has stopped working. The page visits are showing up in the log, but the goal is not being marked. This is still not fixed on b2 either.

**Comment by mattab** [comment]
Hi @ericimprint, thanks for the report! 
We will investigate before 2.15.0 stable.

**Comment by ericimprint** [comment]
FYI, still not working in beta 3.

**Comment by tsteur** [comment]
I tried to reproduce different patterns including a similar one than yours and it worked fine for me. I also debugged it and it should work. From the looks there were also no changes in the `GoalManager` class recently. From which version did you update? 

The only thing that I noticed that could be potentially a problem is the character `&` as it seems to be replaced by an entity before the regexp is checked: `http://apache.piwik/index.php?module=CoreHome&amp;action=index&amp;idSite=1&amp;period=day&amp;date=2015-08-29#/module=Goals&amp;action=goalReport&amp;idSite=1&amp;period=day&amp;date=2015-08-29&amp;idGoal=6`

![image](https://cloud.githubusercontent.com/assets/273120/9561307/0d1e481c-4e40-11e5-9f38-cb2deb5eb8b7.png)

Just to be sure we are talking about URLs and the "matches the expression" check?

**Comment by ericimprint** [comment]
I upgraded from 2.14.3 and it didn't work for any of the 15 betas. 
![goalerror](https://cloud.githubusercontent.com/assets/12055891/9584624/c74f8820-4fd7-11e5-8a4c-fd277f5008a3.jpg)

**Comment by ericimprint** [comment]
I tested this a little more and added the goal again under a new name and added a simple page visit goal. Neither are working, but I did notice `visitor.visitConverted` flag is getting triggered in the live visitor log for visits that trigger the goal. 
The other interesting thing is the goal conversion rate graph is working, but not the reported number in the goal widget of the dashboard. 
![goalerror2](https://cloud.githubusercontent.com/assets/12055891/9586808/87022482-4fe4-11e5-8a4a-cbb2c6c47a8d.jpg)

**Comment by tsteur** [comment]
I just tried to reproduce with `allow multiple conversions` but still works for me. 

Can you maybe change the file `core/Db/Adapter/Pdo/Mysql.php` in line 79 (https://github.com/piwik/piwik/blob/master/core/Db/Adapter/Pdo/Mysql.php#L79) and comment it? Meaning putting `//` in front of `$this->_connection->exec`: `// $this->_connection->exec` and try again?

**Comment by tsteur** [comment]
Otherwise maybe try to enable logging for the tracker: http://developer.piwik.org/api-reference/tracking-api#debugging-the-tracker in case you're familiar with the browser's developer console tool

**Comment by ericimprint** [comment]
>Can you maybe change the file core/Db/Adapter/Pdo/Mysql.php in line 79 (https://github.com/piwik/piwik/blob/master/core/Db/Adapter/Pdo/Mysql.php#L79) and comment it? Meaning putting // in front of $this->_connection->exec: // $this->_connection->exec and try again?
That made no change. 

I turned on debugging and everything is getting passed to piwik correctly. The visits and pages are being logged and marked as a converted goal according to `visitor.visitConverted`. 

I also turned off all 3rd party plugins and that made no difference.

**Comment by tsteur** [comment]
Maybe someone else can have a look and try to reproduce? Not sure what to do here. 

Is it maybe possible that we get access to your Piwik instance and server? That would be helpful. If so, please send us an email to "hello at piwik.org" and comment here in case it goes to the spam folder.

**Comment by ericimprint** [comment]
I did a fresh install of a new testing system. Running 2.14.3 it converted a goal just fine. I upgraded it to beta and the goals stopped converted as above. I emailed the access info for the new testing site to hello. The email came from eric, imprintitems.

**Comment by ericimprint** [comment]
This is not fixed with beta 5. Did you get my email with my testing site info?

**Comment by tsteur** [comment]
Sorry! I got your email but didn't have time yet, will have a look now

**Comment by tsteur** [comment]
Thanks a lot! This helped us to find a bug that would have hit many users over time. I'm getting the following error: 

`Fatal error: Unsupported operand types in core/Tracker/GoalManager.php on line 236` https://github.com/piwik/piwik/blob/2.15.0-b6/core/Tracker/GoalManager.php#L236

The `CustomVariables` plugin is disabled on that system (I checked) and that's why it is failing I believe. This is due to core having knowledge about plugins in https://github.com/piwik/piwik/blob/2.15.0-b6/core/Tracker/GoalManager.php#L227 . Ideally we would remove that knowledge from core but that's probably quite a bit of work and needs some refactoring.

I tried to add a simple check `if (empty($visitCustomVariables)) { $visitCustomVariables = array(); }` but couldn't verify as the PHP files seem to be cached and a server restart is possibly required (or an opcache clearance)

@ericimprint There's a chance that it works after refreshing the webserver. 

@diosmosis do you mind having a look at it? Maybe there are more such similar issues re `$request->getMetadata()`?

**Comment by diosmosis** [comment]
@tsteur created a pull request here: https://github.com/piwik/piwik/pull/8751

I looked at all uses of `Tracker\Request::getMetadata()` this is the only one that assumes the value isn't `empty()`, everything else defaults the value or checks if it's `!empty()` before using it.

**Comment by ericimprint** [comment]
#8751 Does not seem to fix this on my site (test or live) with beta 6.

**Comment by diosmosis** [comment]
Reopening since OP reports it's not fixed for him

**Comment by mattab** [comment]
this change didn't make it in beta6, it was merged after. it will be in beta7. @ericimprint please re-open if it won't be fixed in beta7

**Comment by ericimprint** [comment]
Beta 7 fixed it. Thanks. Not sure why the manual change didn't, but doesn't really matter. Is there anyway to reprocess the visitor data to get the lost goal data back?

**Comment by mattab** [comment]
> Is there anyway to reprocess the visitor data to get the lost goal data back?

unfortunately we don't have this capability yet

**Comment by ericimprint** [comment]
>unfortunately we don't have this capability yet

Bummer.

There is still an error on the dashboard widget. It is showing a graph for the conversion rate, but listing it as a 0%. It is listing it correctly on the goals page/tab.
![goalerror3](https://cloud.githubusercontent.com/assets/12055891/9827344/ea90c416-58a6-11e5-883d-d26733590803.jpg)

**Comment by mattab** [comment]
@ericimprint could you try remove widget and re-add it to dashboard, maybe this fixes it?

**Comment by ericimprint** [comment]
>@ericimprint could you try remove widget and re-add it to dashboard, maybe this fixes it? 

That did the trick. All good. Thanks for your help.
